session_name: reST-lex-byacc
start_directory: ./ # load session relative to config location (project root).
windows:
- window_name: reST-lex-byacc
  focus: True
  layout: main-horizontal
  options:
    main-pane-height: 35
  panes:
  - focus: true
  - pane 
  - make watch_debug
